###eureka 服务端口号
server:
  port: 8100
  ##测试时关闭自我保护机制，保证不可用服务及时剔除
  enable-self-preservation: false
  eviction-interval-timer-in-ms: 2000 ##间隔两秒钟剔除一次
###服务注册名称
eureka:
  instance:
    hostname: server1
###客户端调用地址
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
###因为该应用为注册中心，不会注册自己
    register-with-eureka: false
###因为自己为注册中心 ,不会去在该应用中的检测服务
    fetch-registry: false
  